/*

DO NOT EDIT This file

*/

package main

import "time"

type UserInfo struct {
	ID       int
	Name     string
	Company  string
	Position string
	Address  UserAddress
}
type UserAddress struct {
	AddressNo   string
	SubDistrict string
	District    string
	Province    string
	Postcode    int
}

/*
DO NOT EDIT This function
*/
func GetUserBasicInfo(id int) (UserInfo, error) {
	// Simulate database slow query
	time.Sleep(500 * time.Millisecond)
	user := UserInfo{
		ID:       id,
		Name:     "John Ginger",
		Company:  "JLC Group",
		Position: "Developer",
	}
	return user, nil
}

/*
DO NOT EDIT This function
*/
func GetUserAddress(id int) (UserAddress, error) {
	// Simulate database slow query
	time.Sleep(800 * time.Millisecond)
	userAddress := UserAddress{
		AddressNo:   "62 ซ.นาคนิวาส 6",
		SubDistrict: "ลาดพร้าว",
		District:    "ลาดพร้าว",
		Province:    "กทม",
		Postcode:    10230,
	}
	return userAddress, nil
}
